server:
  port: 8003
spring:
  datasource:
    username: root
    password: "0108"
    url: jdbc:mysql://localhost:3306/allen
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true
    initialization-mode: always
    platform: mysql
    # 执行初始化脚本所在路径
    schema: classpath:schema.sql
    schema-username: root
    schema-password: "0108"